public class demoClass {
	
  
    
    public static void demoMethod1(){
          Blob testVar1 = Blob.valueOf('test');
    Boolean testVar2 = false;
    Date testVar3 = system.today();
    DateTime testVar4 = system.now();
    Decimal testVar5 = 1234.50;
    Double testVar6 = 234324233245345.50;
    Id testVar7 = Id.valueOf('01I3k000003IDxu');
    String testVar8 = 'test';
    Integer testVar9 = 1212;
    Object testVar10 = new Account();
    Long testVar11 = 12312213;
    Time testVar12 = Time.newInstance(01, 0, 0, 0);
   		system.debug(testVar1);
        system.debug(testVar1);
        system.debug(testVar2);
        system.debug(testVar3);
        system.debug(testVar4);
        system.debug(testVar5);
        system.debug(testVar6);
        system.debug(testVar7);
        system.debug(testVar8);
        system.debug(testVar9);
        system.debug(testVar10);
}
}